FROM python:3.7

MAINTAINER Mark Foley

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install libgdal-dev net-tools nginx python-pip uwsgi supervisor
RUN python -m pip install --upgrade pip
#RUN rm -f /etc/nginx/fastcgi.conf /etc/nginx/fastcgi_params && \
#    rm -f /etc/nginx/snippets/fastcgi-php.conf /etc/nginx/snippets/snakeoil.conf

RUN mkdir -p /usr/src/app
RUN useradd -ms /bin/bash webuser

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt

#RUN ln -s /usr/src/app/wmap_201920_django_nginx.conf /etc/nginx/sites-enabled/
#RUN systemctl start nginx

EXPOSE 8011

#EXPOSE 80
#EXPOSE 443

CMD ["uwsgi", "uwsgi.ini"]