# Generated by Django 2.2.5 on 2019-09-30 21:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuts1', models.CharField(max_length=3)),
                ('nuts1name', models.CharField(max_length=10)),
                ('nuts2', models.CharField(max_length=4)),
                ('nuts2name', models.CharField(max_length=30)),
                ('nuts3', models.CharField(max_length=5)),
                ('nuts3name', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=2)),
                ('countyname', models.CharField(max_length=35)),
                ('male2011', models.FloatField()),
                ('female2011', models.FloatField()),
                ('total2011', models.FloatField()),
                ('ppocc2011', models.FloatField()),
                ('unocc2011', models.FloatField()),
                ('hs2011', models.FloatField()),
                ('vacant2011', models.FloatField()),
                ('pcvac2011', models.FloatField()),
                ('total_area', models.FloatField()),
                ('land_area', models.FloatField()),
                ('createdate', models.CharField(max_length=10)),
                ('geogid', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=29903)),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuts1', models.CharField(max_length=3)),
                ('nuts1name', models.CharField(max_length=10)),
                ('nuts2', models.CharField(max_length=4)),
                ('nuts2name', models.CharField(max_length=30)),
                ('nuts3', models.CharField(max_length=5)),
                ('nuts3name', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=2)),
                ('countyname', models.CharField(max_length=35)),
                ('csoed', models.CharField(max_length=15)),
                ('osied', models.CharField(max_length=15)),
                ('edname', models.CharField(max_length=80)),
                ('male2011', models.FloatField()),
                ('female2011', models.FloatField()),
                ('total2011', models.FloatField()),
                ('ppocc2011', models.FloatField()),
                ('unocc2011', models.FloatField()),
                ('hs2011', models.FloatField()),
                ('vacant2011', models.FloatField()),
                ('pcvac2011', models.FloatField()),
                ('total_area', models.FloatField()),
                ('land_area', models.FloatField()),
                ('createdate', models.CharField(max_length=10)),
                ('geogid', models.CharField(max_length=100)),
                ('highered', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=29903)),
            ],
        ),
        migrations.CreateModel(
            name='SmallArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuts1', models.CharField(max_length=3)),
                ('nuts1name', models.CharField(max_length=10)),
                ('nuts2', models.CharField(max_length=4)),
                ('nuts2name', models.CharField(max_length=30)),
                ('nuts3', models.CharField(max_length=5)),
                ('nuts3name', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=2)),
                ('countyname', models.CharField(max_length=35)),
                ('csoed', models.CharField(max_length=15)),
                ('osied', models.CharField(max_length=15)),
                ('edname', models.CharField(max_length=80)),
                ('small_area', models.CharField(max_length=65)),
                ('male2011', models.FloatField()),
                ('female2011', models.FloatField()),
                ('total2011', models.FloatField()),
                ('ppocc2011', models.FloatField()),
                ('unocc2011', models.FloatField()),
                ('hs2011', models.FloatField()),
                ('vacant2011', models.FloatField()),
                ('pcvac2011', models.FloatField()),
                ('createdate', models.CharField(max_length=10)),
                ('geogid', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=29903)),
            ],
        ),
    ]
