# Generated by Django 2.2.5 on 2019-10-01 10:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20191001_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
